from os import getenv
from pathlib import Path
from lion.bootstrap.constants import STATUS_LOG_FILE_NAME
from lion.bootstrap.get_user import retrieve_current_user

USER_ID, USER_NAME, GROUP_NAME = retrieve_current_user()
USER_ID = str(USER_ID).replace(' ','')
USER_NAME = str(USER_NAME).replace(' ','')
GROUP_NAME = str(GROUP_NAME).replace(' ','')

RECOMMENDED_BLOB_CONTAINER = {}

LION_PROJECT_HOME = Path().resolve()
LION_USER_HOME = LION_PROJECT_HOME / USER_NAME

LION_LOGS_PATH = LION_USER_HOME / 'logs'

LION_DRIVER_REPORT_DIST_PATH = LION_PROJECT_HOME / "DriverReportDist"
RECOMMENDED_BLOB_CONTAINER[LION_DRIVER_REPORT_DIST_PATH] = 'Shared'

LION_ARCGIS_PATH = LION_PROJECT_HOME / "ArcGIS"
LION_CONSOLIDATED_REPORT_PATH = LION_PROJECT_HOME / "ConsolidatedReports"
RECOMMENDED_BLOB_CONTAINER[LION_CONSOLIDATED_REPORT_PATH] = 'Shared'

LION_OPTIMIZATION_PATH = LION_USER_HOME / "optimisation"

DELTA_DATA_PATH = LION_USER_HOME / "DeltaData"
DELTA_DATA_LOG_PATH = DELTA_DATA_PATH / "logs"

LION_LOCAL_DRIVER_REPORT_PATH = LION_LOGS_PATH / "DriverReport"
LION_DIAGNOSTICS_PATH = LION_LOGS_PATH / "diagnostics"

lio_pkg_path = Path(getenv('LION_PKG_MODULES_PATH')).resolve()
LION_STATIC_PATH=lio_pkg_path / 'static'
LION_JS_PATH = LION_STATIC_PATH / 'js'
LION_FILES_PATH = LION_STATIC_PATH / 'files'
LION_IMAGES_PATH = LION_STATIC_PATH / 'images'
LION_FONTS_PATH = LION_STATIC_PATH / 'fonts'

# Temporary paths for optimization data dumps
TEMP_APP_DATA_FOLDER = LION_USER_HOME / 'tmp-lion'
LION_TEMP_OPTIMIZATION_DATA_DUMP_PATH = TEMP_APP_DATA_FOLDER / 'TempOptimizationDataDump'
LION_TEMP_DELTA_DATA_DUMP_PATH = TEMP_APP_DATA_FOLDER / 'delta-tmp'

LION_LOG_FILE_PATH = LION_LOGS_PATH / STATUS_LOG_FILE_NAME
LION_OPTIMIZATION_LOG_FILE_PATH = LION_OPTIMIZATION_PATH / 'optimization.log'

for pth in [TEMP_APP_DATA_FOLDER, LION_TEMP_OPTIMIZATION_DATA_DUMP_PATH, LION_TEMP_DELTA_DATA_DUMP_PATH,
            LION_DIAGNOSTICS_PATH, LION_LOCAL_DRIVER_REPORT_PATH, DELTA_DATA_LOG_PATH, DELTA_DATA_PATH,
            LION_OPTIMIZATION_PATH, LION_CONSOLIDATED_REPORT_PATH, LION_DRIVER_REPORT_DIST_PATH, LION_LOGS_PATH, 
            LION_USER_HOME]:
    
    pth.mkdir(parents=True, exist_ok=True)

from lion.logger.logger_handler import initialize_logger
initialize_logger(log_file_path=LION_LOG_FILE_PATH, user_name=USER_NAME)
