name: Build and deploy Python app to Azure Web App - lion

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lion
  PYTHON_VSN: '3.12'
  AZURE_RESOURCE_GROUP: rg-lion-app


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VSN }}

      # - name: Install dependencies
      - name: Install dependencies and package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools
          pip install .
          pip show ${{ env.AZURE_WEBAPP_NAME }}
          echo "${{ env.AZURE_WEBAPP_NAME }} installed; skipping app import due to missing env vars."

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: |
            .
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_LION_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_LION_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # Dynamically set Azure App Settings before deployment
      - name: Configure Azure App Settings
        run: |
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITES_DISABLE_ORYX=false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
