name: Build and deploy Python app to Azure Web App - lion

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lion
  PYTHON_VSN: '3.12'
  AZURE_RESOURCE_GROUP: rg-lion-app
  WEBSITES_CONTAINER_START_TIME_LIMIT: 188
  WEBSITES_ENABLE_APP_SERVICE_STORAGE: false
  WEBSITES_PORT: 8000
  FLASK_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VSN }}

      # - name: Install dependencies
      - name: Install dependencies and package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools
          pip install .
          pip show ${{ env.AZURE_WEBAPP_NAME }}
          echo "${{ env.AZURE_WEBAPP_NAME }} installed; skipping app import due to missing env vars."

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: |
            .
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B026A751B2C41CB904E28DFBE0BF0A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1EA8B0CB0A6452EB61D86EC2166F59A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F366397AB794420AE9F78492E6DFA18 }}


      # Dynamically set Azure App Settings before deployment
      - name: Configure Azure App Settings
        run: |
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITES_DISABLE_ORYX=false \
            AZURE_SQL_USER=${{ secrets.AZURE_SQL_USER }} AZURE_SQL_PASS=${{ secrets.AZURE_SQL_PASS }} AZURE_SQL_SERVER=${{ secrets.AZURE_SQL_SERVER }} AZURE_SQL_DB=${{ secrets.AZURE_SQL_DB }} \
            AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }} AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }} AZURE_SUBSCRIPTION=${{ secrets.AZURE_SUBSCRIPTION }} \
            AZURE_LION_APP_TENANT_ID=${{ secrets.AZURE_LION_APP_TENANT_ID }} AZURE_LION_APP_CLIENT_ID=${{ secrets.AZURE_LION_APP_CLIENT_ID }} \
            AZURE_LION_APP_OBJECT_ID=${{ secrets.AZURE_LION_APP_OBJECT_ID }} AZURE_LION_APP_CLIENT_SECRET=${{ secrets.AZURE_LION_APP_CLIENT_SECRET }} FLASK_ENV=${{env.FLASK_ENV}} \
            FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} WEBSITES_CONTAINER_START_TIME_LIMIT=${{ env.WEBSITES_CONTAINER_START_TIME_LIMIT }} \
            AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} WEBSITES_ENABLE_APP_SERVICE_STORAGE=${{env.WEBSITES_ENABLE_APP_SERVICE_STORAGE}} \
            WEBSITES_PORT=${{env.WEBSITES_PORT}}  PORT=${{env.WEBSITES_PORT}} 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
