name: Build and deploy Python app to Azure Web App - lion

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # - name: Install dependencies
      - name: Install dependencies and package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools
          pip install .
          pip show lion
          python -c "from lion.lion_app import app; print(f'✅ lion.app loaded: {type(app)}')"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: lion-flask-app
          path: |
            .
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: lion-flask-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B026A751B2C41CB904E28DFBE0BF0A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1EA8B0CB0A6452EB61D86EC2166F59A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F366397AB794420AE9F78492E6DFA18 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lion'
          slot-name: 'Production'
